http_port 3128

# Allow all connections
acl all src all
http_access allow all

# No logging
access_log none
cache_log /dev/null
cache_store_log none

# No caching
no_cache deny all
cache deny all

# Forward proxy settings
via off
forwarded_for delete
follow_x_forwarded_for deny all
