http_port 3128

# Allow all connections
acl localnet src 0.0.0.1-0.255.255.255
acl localnet src 10.0.0.0/8
acl localnet src 100.64.0.0/10
acl localnet src 169.254.0.0/16
acl localnet src 172.16.0.0/12
acl localnet src 192.168.0.0/16
acl localnet src fc00::/7
acl localnet src fe80::/10
acl SSL_ports port 443
acl Safe_ports port 80
acl Safe_ports port 443
acl Safe_ports port 1025-65535
acl CONNECT method CONNECT

http_access allow all

# No logging
access_log none
cache_log /dev/null
cache_store_log none

# No caching
no_cache deny all
cache deny all

# Hide proxy info
via off
forwarded_for delete
follow_x_forwarded_for deny all